"""External device ports used by V1 behavior modules."""

from __future__ import annotations

from typing import Protocol


class RobotAdapter(Protocol):
    def perform_downward_dog_combo(self, correlation_id: str) -> None: ...

    def perform_push_up(self, correlation_id: str) -> None: ...

    def sit_and_watch_user(self, correlation_id: str) -> None: ...

    def lay_down_and_watch_user(self, correlation_id: str) -> None: ...

    def celebrate_happy(self, correlation_id: str) -> None: ...

    def high_five_left(self, correlation_id: str) -> None: ...

    def high_five_right(self, correlation_id: str) -> None: ...

    def stop_motion(self, reason: str) -> None: ...


class PhotoCapture(Protocol):
    def capture(self, correlation_id: str) -> str: ...


class DisplayAdapter(Protocol):
    def blink_then_flash(self, correlation_id: str) -> None: ...


class VoiceAdapter(Protocol):
    def speak(self, text: str, correlation_id: str) -> None: ...
